language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: CODESTYLE="yes"
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - composer self-update --no-interaction
  - travis_retry composer update --no-suggest --no-interaction

script:
  - if [[ $CODESTYLE != "yes" ]]; then composer test; else composer cs; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
